application: sshz-docs
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /themes/(.*?)/static/(.*)
  static_files: themes/\1/static/\2
  upload: themes/(.*?)/static/(.*)

- url: /.*
  script: main.application
